# default guidelines taken from https://github.com/bjankord/stylelint-config-sass-guidelines
extends: "stylelint-config-sass-guidelines"
# ignoreFiles: ["**/node_modules/*.*"] # stylelint ignores this by default
# defaultSeverity: "warning"
plugins: [
  "stylelint-no-unsupported-browser-features",
  # "stylelint-selector-no-empty",
  "stylelint-use-nesting"
]

# for a list of rules => https://stylelint.io/user-guide/rules/list
# and https://github.com/bjankord/stylelint-config-sass-guidelines
# https://github.com/bjankord/stylelint-config-sass-guidelines/blob/main/src/.stylelintrc.json
rules:
  # first of all, plugin-related rules
  plugin/no-unsupported-browser-features:
    - true
    - severity: warning
#  plugin/stylelint-selector-no-empty: true
#  # comes with the extended guideline
#  order/properties-alphabetical-order: null
  scss/at-mixin-pattern: "^[a-z][a-zA-Z0-9]*$"
  # /* */ comments are written to css files under circumstances, therefore avoid
  scss/comment-no-loud: true
  scss/dollar-variable-pattern:
    - "^[a-z][a-zA-Z0-9]*$"
    - message: "The name of the variable has to follow camelCase syntax "
  scss/double-slash-comment-empty-line-before:
    ["always", {
      except: ["inside-block"],
      ignore: ["between-comments"]
    }]
  scss/selector-no-redundant-nesting-selector:
    - true
    - severity: warning
  csstools/use-nesting: ["always", { "except": ['&:hover']}]
  #########################################################################################################
  #################### stylelint or stylelint-config-sass-guidelines rules from here ######################
  #########################################################################################################
  block-closing-brace-empty-line-before: never
  block-opening-brace-newline-after: always
  color-named:
    - "never"
    - message: "named colors are not permitted "
  color-no-hex: true
  comment-no-empty: true
  ############### the following commented out rules are turned on by default via the extended config ###############
  declaration-colon-space-after: always
  declaration-block-no-duplicate-properties:
    - true
    # *IF* there is a need to support older browsers and there is a fallback for a property
    - ignore: ["consecutive-duplicates"]
  # don't allow !important statement
  declaration-no-important:
    [true, {
        message: "Please try to avoid !important under all circumstances, Don't use it. It's vicious! VICIOUS!",
        severity: warning
    }]
  font-family-no-missing-generic-family-keyword: true
  # lowercase syntax for function-names.
  function-name-case:
    - lower
    - ignoreFunctions:
        - "pxToEm"
        - "pxToRem"
        - "^[a-z][a-zA-Z0-9]*$"
  indentation:
    - 2
    - message: "indentation must not be different than 2 spaces"
  max-empty-lines:
    - 2
    - ignore: ["comments"]
  max-line-length: [
    140, {
    ignore: ["comments"],
    severity: warning
  }]
  max-nesting-depth:
    - 3
    - severity: warning
  no-empty-first-line:
    - true
    - message: "The file must not begin with a blank line"
  no-eol-whitespace: true
  no-extra-semicolons: true
  no-unknown-animations: true
  number-leading-zero: "never"
  rule-empty-line-before:
    - "always"
    - ignore: ["after-comment", "first-nested", "inside-block"]
  # lowercase hyphenated for class selectors, e.g. .test-element
  selector-class-pattern:
    - "^[a-z0-9\\-]+$"
  selector-no-qualifying-type:
    - true
    - severity: warning
      message: "Selectors must not include an extra qualifying type-selector "
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements: ["ng-deep"]
  selector-max-id: 1
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-quotes: always
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-max-compound-selectors:
    - 4
    - severity: warning
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-type-case: lower
  selector-list-comma-newline-after: always
  selector-list-comma-space-after: always-single-line
  unit-allowed-list: ["em", "rem", "px", "vh", "vw", "ms" , "s", "%", "deg", "fr"]
