
CREATE TABLE SUMMARY_PER_DAY (
    DATE DATE PRIMARY KEY NOT NULL,
    PRODUCTION_WATT_HOURS INTEGER NOT NULL,
    SALE_WATT_HOURS INTEGER NOT NULL,
    SELF_CONSUMPTION_WATT_HOURS INTEGER NOT NULL,
    PURCHASE_WATT_HOURS INTEGER NOT NULL,
    CONSUMPTION_WATT_HOURS INTEGER NOT NULL,
    AUTARCHY DOUBLE PRECISION NOT NULL,
    ACCUMULATED_PRODUCTION_WATT_HOURS INTEGER NOT NULL,
    ACCUMULATED_SALE_WATT_HOURS INTEGER NOT NULL,
    ACCUMULATED_SELF_CONSUMPTION_WATT_HOURS INTEGER NOT NULL,
    ACCUMULATED_PURCHASE_WATT_HOURS INTEGER NOT NULL,
    ACCUMULATED_CONSUMPTION_WATT_HOURS INTEGER NOT NULL,
    YEAR_OF_ENTRY INTEGER NOT NULL,
    MONTH_OF_ENTRY INTEGER NOT NULL
);