
CREATE TABLE RETURN_ON_INVESTMENT (
    ID INTEGER PRIMARY KEY NOT NULL,
    DATE DATE,
    AMOUNT_IN_MINOR_UNIT INTEGER NOT NULL,
    AMOUNT_IS_POSITIVE BOOLEAN NOT NULL,
    DESCRIPTION VARCHAR NOT NULL
);