CREATE TABLE ENERGY_SALE_COMPENSATION (
    ID INTEGER PRIMARY KEY NOT NULL,
    COMPENSATION_DATE DATE NOT NULL,
    PRODUCTION_FROM_DATE DATE NOT NULL,
    PRODUCTION_TO_DATE DATE NOT NULL,
    PRODUCTION_YEAR INTEGER NOT NULL,
    COMPENSATION_AMOUNT_IN_MINOR_UNIT INTEGER NOT NULL
);